spring:
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/billim
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true