cloud:
  aws:
    s3:
      bucket: billim
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIA4RHHLKCV3UJG647D
      secret-key: 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